//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SDG_DEMO.TRFws {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsTRFRichiestaSoap", Namespace="http://www.sdgitaly.net/")]
    public partial class wsTRFRichiesta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WsNuovaRichiestaOperationCompleted;
        
        private System.Threading.SendOrPostCallback WsModificaRichiestaOperationCompleted;
        
        private System.Threading.SendOrPostCallback WsAnnullaRichiestaOperationCompleted;
        
        private System.Threading.SendOrPostCallback WsSbloccaRichiestaOperationCompleted;
        
        private System.Threading.SendOrPostCallback WsVisualizzaRichiestaOperationCompleted;
        
        private System.Threading.SendOrPostCallback WsRichiestaFruitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback WsRichiestaNonFruitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback WsNotificaRichiesteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsTRFRichiesta() {
            this.Url = global::SDG_DEMO.Properties.Settings.Default.TRF_TRFws_wsTRFRichiesta;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WsNuovaRichiestaCompletedEventHandler WsNuovaRichiestaCompleted;
        
        /// <remarks/>
        public event WsModificaRichiestaCompletedEventHandler WsModificaRichiestaCompleted;
        
        /// <remarks/>
        public event WsAnnullaRichiestaCompletedEventHandler WsAnnullaRichiestaCompleted;
        
        /// <remarks/>
        public event WsSbloccaRichiestaCompletedEventHandler WsSbloccaRichiestaCompleted;
        
        /// <remarks/>
        public event WsVisualizzaRichiestaCompletedEventHandler WsVisualizzaRichiestaCompleted;
        
        /// <remarks/>
        public event WsRichiestaFruitaCompletedEventHandler WsRichiestaFruitaCompleted;
        
        /// <remarks/>
        public event WsRichiestaNonFruitaCompletedEventHandler WsRichiestaNonFruitaCompleted;
        
        /// <remarks/>
        public event WsNotificaRichiesteCompletedEventHandler WsNotificaRichiesteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sdgitaly.net/WsNuovaRichiesta", RequestNamespace="http://www.sdgitaly.net/", ResponseNamespace="http://www.sdgitaly.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WsNuovaRichiesta(System.Data.DataSet dsRichiesta) {
            object[] results = this.Invoke("WsNuovaRichiesta", new object[] {
                        dsRichiesta});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WsNuovaRichiestaAsync(System.Data.DataSet dsRichiesta) {
            this.WsNuovaRichiestaAsync(dsRichiesta, null);
        }
        
        /// <remarks/>
        public void WsNuovaRichiestaAsync(System.Data.DataSet dsRichiesta, object userState) {
            if ((this.WsNuovaRichiestaOperationCompleted == null)) {
                this.WsNuovaRichiestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsNuovaRichiestaOperationCompleted);
            }
            this.InvokeAsync("WsNuovaRichiesta", new object[] {
                        dsRichiesta}, this.WsNuovaRichiestaOperationCompleted, userState);
        }
        
        private void OnWsNuovaRichiestaOperationCompleted(object arg) {
            if ((this.WsNuovaRichiestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsNuovaRichiestaCompleted(this, new WsNuovaRichiestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sdgitaly.net/WsModificaRichiesta", RequestNamespace="http://www.sdgitaly.net/", ResponseNamespace="http://www.sdgitaly.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WsModificaRichiesta(System.Data.DataSet dsRichiesta) {
            object[] results = this.Invoke("WsModificaRichiesta", new object[] {
                        dsRichiesta});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WsModificaRichiestaAsync(System.Data.DataSet dsRichiesta) {
            this.WsModificaRichiestaAsync(dsRichiesta, null);
        }
        
        /// <remarks/>
        public void WsModificaRichiestaAsync(System.Data.DataSet dsRichiesta, object userState) {
            if ((this.WsModificaRichiestaOperationCompleted == null)) {
                this.WsModificaRichiestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsModificaRichiestaOperationCompleted);
            }
            this.InvokeAsync("WsModificaRichiesta", new object[] {
                        dsRichiesta}, this.WsModificaRichiestaOperationCompleted, userState);
        }
        
        private void OnWsModificaRichiestaOperationCompleted(object arg) {
            if ((this.WsModificaRichiestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsModificaRichiestaCompleted(this, new WsModificaRichiestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sdgitaly.net/WsAnnullaRichiesta", RequestNamespace="http://www.sdgitaly.net/", ResponseNamespace="http://www.sdgitaly.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WsAnnullaRichiesta(string IdMissione) {
            object[] results = this.Invoke("WsAnnullaRichiesta", new object[] {
                        IdMissione});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WsAnnullaRichiestaAsync(string IdMissione) {
            this.WsAnnullaRichiestaAsync(IdMissione, null);
        }
        
        /// <remarks/>
        public void WsAnnullaRichiestaAsync(string IdMissione, object userState) {
            if ((this.WsAnnullaRichiestaOperationCompleted == null)) {
                this.WsAnnullaRichiestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsAnnullaRichiestaOperationCompleted);
            }
            this.InvokeAsync("WsAnnullaRichiesta", new object[] {
                        IdMissione}, this.WsAnnullaRichiestaOperationCompleted, userState);
        }
        
        private void OnWsAnnullaRichiestaOperationCompleted(object arg) {
            if ((this.WsAnnullaRichiestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsAnnullaRichiestaCompleted(this, new WsAnnullaRichiestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sdgitaly.net/WsSbloccaRichiesta", RequestNamespace="http://www.sdgitaly.net/", ResponseNamespace="http://www.sdgitaly.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WsSbloccaRichiesta(string IdMissione) {
            object[] results = this.Invoke("WsSbloccaRichiesta", new object[] {
                        IdMissione});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WsSbloccaRichiestaAsync(string IdMissione) {
            this.WsSbloccaRichiestaAsync(IdMissione, null);
        }
        
        /// <remarks/>
        public void WsSbloccaRichiestaAsync(string IdMissione, object userState) {
            if ((this.WsSbloccaRichiestaOperationCompleted == null)) {
                this.WsSbloccaRichiestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsSbloccaRichiestaOperationCompleted);
            }
            this.InvokeAsync("WsSbloccaRichiesta", new object[] {
                        IdMissione}, this.WsSbloccaRichiestaOperationCompleted, userState);
        }
        
        private void OnWsSbloccaRichiestaOperationCompleted(object arg) {
            if ((this.WsSbloccaRichiestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsSbloccaRichiestaCompleted(this, new WsSbloccaRichiestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sdgitaly.net/WsVisualizzaRichiesta", RequestNamespace="http://www.sdgitaly.net/", ResponseNamespace="http://www.sdgitaly.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WsVisualizzaRichiesta(string IdMissione) {
            object[] results = this.Invoke("WsVisualizzaRichiesta", new object[] {
                        IdMissione});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WsVisualizzaRichiestaAsync(string IdMissione) {
            this.WsVisualizzaRichiestaAsync(IdMissione, null);
        }
        
        /// <remarks/>
        public void WsVisualizzaRichiestaAsync(string IdMissione, object userState) {
            if ((this.WsVisualizzaRichiestaOperationCompleted == null)) {
                this.WsVisualizzaRichiestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsVisualizzaRichiestaOperationCompleted);
            }
            this.InvokeAsync("WsVisualizzaRichiesta", new object[] {
                        IdMissione}, this.WsVisualizzaRichiestaOperationCompleted, userState);
        }
        
        private void OnWsVisualizzaRichiestaOperationCompleted(object arg) {
            if ((this.WsVisualizzaRichiestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsVisualizzaRichiestaCompleted(this, new WsVisualizzaRichiestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sdgitaly.net/WsRichiestaFruita", RequestNamespace="http://www.sdgitaly.net/", ResponseNamespace="http://www.sdgitaly.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WsRichiestaFruita(string IdMissione) {
            object[] results = this.Invoke("WsRichiestaFruita", new object[] {
                        IdMissione});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WsRichiestaFruitaAsync(string IdMissione) {
            this.WsRichiestaFruitaAsync(IdMissione, null);
        }
        
        /// <remarks/>
        public void WsRichiestaFruitaAsync(string IdMissione, object userState) {
            if ((this.WsRichiestaFruitaOperationCompleted == null)) {
                this.WsRichiestaFruitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsRichiestaFruitaOperationCompleted);
            }
            this.InvokeAsync("WsRichiestaFruita", new object[] {
                        IdMissione}, this.WsRichiestaFruitaOperationCompleted, userState);
        }
        
        private void OnWsRichiestaFruitaOperationCompleted(object arg) {
            if ((this.WsRichiestaFruitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsRichiestaFruitaCompleted(this, new WsRichiestaFruitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sdgitaly.net/WsRichiestaNonFruita", RequestNamespace="http://www.sdgitaly.net/", ResponseNamespace="http://www.sdgitaly.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WsRichiestaNonFruita(string IdMissione) {
            object[] results = this.Invoke("WsRichiestaNonFruita", new object[] {
                        IdMissione});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WsRichiestaNonFruitaAsync(string IdMissione) {
            this.WsRichiestaNonFruitaAsync(IdMissione, null);
        }
        
        /// <remarks/>
        public void WsRichiestaNonFruitaAsync(string IdMissione, object userState) {
            if ((this.WsRichiestaNonFruitaOperationCompleted == null)) {
                this.WsRichiestaNonFruitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsRichiestaNonFruitaOperationCompleted);
            }
            this.InvokeAsync("WsRichiestaNonFruita", new object[] {
                        IdMissione}, this.WsRichiestaNonFruitaOperationCompleted, userState);
        }
        
        private void OnWsRichiestaNonFruitaOperationCompleted(object arg) {
            if ((this.WsRichiestaNonFruitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsRichiestaNonFruitaCompleted(this, new WsRichiestaNonFruitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sdgitaly.net/WsNotificaRichieste", RequestNamespace="http://www.sdgitaly.net/", ResponseNamespace="http://www.sdgitaly.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WsNotificaRichieste(string userName, string domainName) {
            object[] results = this.Invoke("WsNotificaRichieste", new object[] {
                        userName,
                        domainName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WsNotificaRichiesteAsync(string userName, string domainName) {
            this.WsNotificaRichiesteAsync(userName, domainName, null);
        }
        
        /// <remarks/>
        public void WsNotificaRichiesteAsync(string userName, string domainName, object userState) {
            if ((this.WsNotificaRichiesteOperationCompleted == null)) {
                this.WsNotificaRichiesteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsNotificaRichiesteOperationCompleted);
            }
            this.InvokeAsync("WsNotificaRichieste", new object[] {
                        userName,
                        domainName}, this.WsNotificaRichiesteOperationCompleted, userState);
        }
        
        private void OnWsNotificaRichiesteOperationCompleted(object arg) {
            if ((this.WsNotificaRichiesteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsNotificaRichiesteCompleted(this, new WsNotificaRichiesteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void WsNuovaRichiestaCompletedEventHandler(object sender, WsNuovaRichiestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsNuovaRichiestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsNuovaRichiestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void WsModificaRichiestaCompletedEventHandler(object sender, WsModificaRichiestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsModificaRichiestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsModificaRichiestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void WsAnnullaRichiestaCompletedEventHandler(object sender, WsAnnullaRichiestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsAnnullaRichiestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsAnnullaRichiestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void WsSbloccaRichiestaCompletedEventHandler(object sender, WsSbloccaRichiestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsSbloccaRichiestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsSbloccaRichiestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void WsVisualizzaRichiestaCompletedEventHandler(object sender, WsVisualizzaRichiestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsVisualizzaRichiestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsVisualizzaRichiestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void WsRichiestaFruitaCompletedEventHandler(object sender, WsRichiestaFruitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsRichiestaFruitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsRichiestaFruitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void WsRichiestaNonFruitaCompletedEventHandler(object sender, WsRichiestaNonFruitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsRichiestaNonFruitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsRichiestaNonFruitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void WsNotificaRichiesteCompletedEventHandler(object sender, WsNotificaRichiesteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsNotificaRichiesteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsNotificaRichiesteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591